name: Build using Intel drivers

on:
  push:
    branches: [ master, dev*, ow* ]
  pull_request:
    branches: [ master, dev, ow* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, ubuntu-20.04 ]

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - uses: actions/checkout@v3

    - name: Install Intel OpenCL libraries needed for Sibernetic
      run: |

        lscpu

        echo "Installing OpenCL Drivers"

        # Based on: https://github.com/openworm/OpenWorm/blob/master/Dockerfile

        mkdir intel-opencl-tmp
        cd intel-opencl-tmp
        mkdir intel-opencl
        wget https://github.com/openworm/OpenWorm/raw/dev_inte/SRB5.0_linux64.zip
        unzip SRB5.0_linux64.zip
        tar -C intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
        sudo cp -R intel-opencl/* /
        sudo ldconfig
        cd ..
        sudo rm -r intel-opencl-tmp

        sudo cp -R /opt/intel/opencl/include/CL /usr/include/
        sudo apt install -y ocl-icd-opencl-dev vim

        echo "OpenCL Driver Installation Complete"


    - name: Build Sibernetic
      run: |

        sudo apt install -y python3-dev freeglut3-dev libglu1-mesa-dev
        #sudo apt install -y  --allow-downgrades libc-bin=2.27-3ubuntu1.5 # Fails with 2.27-3ubuntu1.6 for some reason...
        python -V
        ls -alt /usr/bin/python*
        ls -alt
        make clean
        make

    - name: Print info on executable
      run: |
        ldd ./Release/Sibernetic

        echo "NOTE: not running Sibernetic on GitHub actions test with Intel drivers. Seg faults."
        ###./Release/Sibernetic -no_g timelimit=0.001

    - name: Final version info
      run: |

        python -V
        pip list
